name: Jira Integration

on:
  pull_request:
    types: [closed]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue Key
        run: |
          JIRA_ISSUE=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "JIRA_ISSUE=$JIRA_ISSUE" >> $GITHUB_ENV

      - name: Transition Jira Issue to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_ISSUE }}
          transition: "Done"
        env:
          JIRA_BASE_URL: "https://aso-wysofia-start.atlassian.net"
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}